#!/usr/bin/env sh
set -e

# Gradle start up script for UN*X
# Generated by Gradle 8.6

progname="$(basename "$0")"
basedir=$(dirname "$0")

# Resolve links - $0 may be a link
while [ -h "$basedir" ] ; do
  ls=$(ls -ld "$basedir")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    basedir="$link"
  else
    basedir=$(dirname "$basedir")/"$link"
  fi
done

if [ "x$JAVA_HOME" = "x" ]; then
  JAVA_CMD=java
else
  JAVA_CMD="$JAVA_HOME/bin/java"
fi

CLASSPATH="$basedir/gradle/wrapper/gradle-wrapper.jar"

exec "$JAVA_CMD" -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
